### ISSUE TITLE
Second indicator on analog clock

### ISSUE THREAD

**Issue by FredericG-BE** [FredericG-BE/OpenHasp-HA-pyscript#15]

**Comment by vmfs1968** [comment]
Second indicator on analog clock
Yes, I would really like to have this function

**Comment by FredericG-BE** [comment]
Implemented the AnalogClock showSec option: https://github.com/FredericG-BE/OpenHasp-HA-pyscript/commit/b81169abecd9703e5ad005e3a290be5596282dba
